### ISSUE TITLE
Add way to inject HTML tags into new questions

### ISSUE THREAD

**Issue by WZWren** [CS3219-AY2425S1/cs3219-ay2425s1-project-g14#30]
> We need a way to inject the HTML input for making a new question for formatting, if we use a structure inspired by the LeetCode API. The existing new question should work fine, but it will not format nicely. Considering the only kinds of people adding questions likely will have access to the backend, we will put this as a nice-to-have.

_Originally posted by @WZWren in https://github.com/CS3219-AY2425S1/cs3219-ay2425s1-project-g14/pull/29#discussion_r1788922890_

**Comment by rertyy** [comment]
Fixed in https://github.com/CS3219-AY2425S1/cs3219-ay2425s1-project-g14/pull/51
